from typing import Optional, List, Any
from typing_extensions import Literal
from langgraph.graph import MessagesState
from pydantic import BaseModel, Field


class AgentState(MessagesState):
    """Main agent state - extends MessagesState for passing messages between nodes.
    
    All agent nodes should use this state type for consistent message handling.
    """
    is_profiling: Optional[bool]
    username: Optional[str]  # Extracted username from profiling query
    start_time: Optional[str]  # ISO time for start
    end_time: Optional[str]  # ISO time for end
    tool_iteration_count: Optional[int] = 0  # Track tool loop iterations
    plan: Optional[str] = None  # Generated plan for tool usage
    tools_missing: Optional[bool] = None  # True if required tools are missing from plan analysis


class AgentOutputState(BaseModel):
    """Final output schema for API responses or downstream consumers.
    
    Captures the agent's best-effort extracted time window and a placeholder
    summary for profiling data (to be implemented later).
    """
    username: Optional[str] = Field(description="Extracted username for the request", default=None)
    start_time: Optional[str] = Field(description="Final start time in ISO 8601 if available", default=None)
    end_time: Optional[str] = Field(description="Final end time in ISO 8601 if available", default=None)
    agent_summary: str = Field(description="Final summary returned by the agent (may include placeholder)", default="")
    status: str = Field(description="Overall status for the response", default="success")
    messages: List[Any] = Field(description="Full message chain from the conversation", default_factory=list)


class ProfilingQueryClassification(BaseModel):
    """Classifies whether a user query is about profiling or not."""
    is_profiling: bool = Field(description="True if the query is about profiling, performance analysis, CPU usage, or similar performance-related topics")
    confidence: float = Field(description="Confidence score between 0 and 1", ge=0.0, le=1.01)


class MetadataExtraction(BaseModel):
    """Extracts username and times from the conversation."""
    username: Optional[str] = Field(description="Username extracted from the user's message, or None if not found", default=None)
    start_time: Optional[str] = Field(description="Start time in ISO 8601 format extracted from the conversation, or None if not found", default=None)
    end_time: Optional[str] = Field(description="End time in ISO 8601 format extracted from the conversation, or None if not found", default=None)


class FinalizeOutput(BaseModel):
    """Final message and status generated by LLM."""
    agent_summary: str = Field(description="Final summary summarizing what was accomplished and the final result")
    status: str = Field(description="Status: 'success' if the task was completed successfully, otherwise 'partial'")


class AgentReasoning(BaseModel):
    """Two-sentence reasoning about agent's actions."""
    reasoning: str = Field(description="Two sentences: first reflects on what the agent already knows from the conversation, second describes what it plans to achieve with the next tool call (if any), or what conclusion it has reached if no tool call is needed")


class PlanAnalysisResult(BaseModel):
    """Structured result for plan analysis."""
    decision: Literal["MISSING_TOOLS", "ALL_TOOLS_AVAILABLE"] = Field(description="Outcome of plan analysis")
    details: Optional[str] = Field(description="Explanation and any missing tool names with expected behavior", default=None)

